"""initial_schema

Revision ID: ad8911fa577b
Revises:
Create Date: 2026-07-06 17:34:58.967751

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad8911fa577b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agreement_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("agreement_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("scope", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "deliverables_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("revision_limit", sa.Integer(), nullable=True),
        sa.Column("fee_amount_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("payment_terms", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("effective_start_date", sa.Date(), nullable=True),
        sa.Column(
            "milestone_plan_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "status",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("activated_at", sa.DateTime(), nullable=True),
        sa.Column("deliverables", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("deadline", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column(
            "acceptance_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PENDING_SIGNATURE', "
            "'PARTIALLY_ACCEPTED', 'ACTIVE', 'SUPERSEDED')",
            name="ck_agreement_status",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "version_number", name="uq_project_version"),
    )
    op.create_index(
        "uq_active_agreement",
        "agreement_versions",
        ["project_id"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
        sqlite_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("client_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "source_platform", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "automation_enabled", sa.Boolean(), server_default="0", nullable=False
        ),
        sa.Column("active_agreement_version_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deadline", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "invoice_due_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("dispute_flag", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "latest_policy_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.CheckConstraint(
            "status IN ('DISCUSSION_CAPTURED', 'TERMS_REVIEW', "
            "'CONTRACT_PENDING_SIGNATURE', 'ACTIVE', 'COMPLETED', "
            "'CLOSED', 'SCOPE_CHANGE_PENDING', 'PAUSED', 'DRAFT', "
            "'TERMS_READY', 'ACCEPTANCE_PENDING', 'ACCEPTED', "
            "'IN_PROGRESS', 'DELIVERED', 'INVOICED', 'OVERDUE', "
            "'DISPUTED', 'RESOLUTION_PENDING')",
            name="ck_project_status",
        ),
        sa.ForeignKeyConstraint(
            ["active_agreement_version_id"],
            ["agreement_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("actor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("metadata_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "communication_drafts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("draft_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("audit_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evidence_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "milestones",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("agreement_version_id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("due_at", sa.DateTime(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("completion_recorded_at", sa.DateTime(), nullable=True),
        sa.Column("recorded_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.CheckConstraint(
            "recorded_by IS NULL OR recorded_by IN ('freelancer', 'system_demo')",
            name="ck_milestone_recorded_by",
        ),
        sa.CheckConstraint(
            "status IN ('PLANNED', 'IN_PROGRESS', "
            "'READY_FOR_REVIEW', 'COMPLETED', 'BLOCKED')",
            name="ck_milestone_status",
        ),
        sa.ForeignKeyConstraint(
            ["agreement_version_id"],
            ["agreement_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "signature_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agreement_version_id", sa.Uuid(), nullable=False),
        sa.Column("party_role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "signer_display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column(
            "acceptance_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.CheckConstraint(
            "party_role IN ('freelancer', 'client')", name="ck_signature_party_role"
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted')", name="ck_signature_status"
        ),
        sa.ForeignKeyConstraint(
            ["agreement_version_id"],
            ["agreement_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "agreement_version_id", "party_role", name="uq_agreement_role"
        ),
    )
    op.create_table(
        "client_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("agreement_version_id", sa.Uuid(), nullable=False),
        sa.Column("milestone_id", sa.Uuid(), nullable=True),
        sa.Column("message_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("send_mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.Column(
            "idempotency_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.CheckConstraint(
            "send_mode IN ('routine_auto', 'approval_required')",
            name="ck_message_send_mode",
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'QUEUED', 'DELIVERED_TO_DEMO_INBOX', "
            "'ACKNOWLEDGED', 'APPROVED', 'APPROVAL_REQUIRED', 'CANCELLED')",
            name="ck_message_status",
        ),
        sa.ForeignKeyConstraint(
            ["agreement_version_id"],
            ["agreement_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["milestone_id"],
            ["milestones.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_table(
        "client_replies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("client_message_id", sa.Uuid(), nullable=True),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("classification", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("possible_scope_change", sa.Boolean(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_message_id"],
            ["client_messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scope_change_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("source_reply_id", sa.Uuid(), nullable=True),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("proposed_contract_version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "affected_milestone_ids_json",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column("initiated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "initiated_by IN ('freelancer', 'client')",
            name="ck_scope_change_initiated_by",
        ),
        sa.CheckConstraint(
            "status IN ('detected', 'pending_review', 'accepted', 'rejected')",
            name="ck_scope_change_status",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proposed_contract_version_id"],
            ["agreement_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_reply_id"],
            ["client_replies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # Establish triggers to protect audit_events
    op.execute("""
        CREATE TRIGGER prevent_audit_update
        BEFORE UPDATE ON audit_events
        BEGIN
            SELECT RAISE(ABORT, 'Updates on audit_events are not allowed');
        END;
    """)
    op.execute("""
        CREATE TRIGGER prevent_audit_delete
        BEFORE DELETE ON audit_events
        BEGIN
            SELECT RAISE(ABORT, 'Deletions on audit_events are not allowed');
        END;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS prevent_audit_update")
    op.execute("DROP TRIGGER IF EXISTS prevent_audit_delete")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scope_change_requests")
    op.drop_table("client_replies")
    op.drop_table("client_messages")
    op.drop_table("signature_records")
    op.drop_table("milestones")
    op.drop_table("evidence_events")
    op.drop_table("communication_drafts")
    op.drop_table("audit_events")
    op.drop_table("projects")
    op.drop_index(
        "uq_active_agreement",
        table_name="agreement_versions",
        postgresql_where=sa.text("status = 'ACTIVE'"),
        sqlite_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_table("agreement_versions")
    # ### end Alembic commands ###
