"""add_mcp_discussion_snapshot_and_milestone_key

Revision ID: aff46b700adb
Revises: ad8911fa577b
Create Date: 2026-07-06 18:06:07.900559

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aff46b700adb"
down_revision: str | Sequence[str] | None = "ad8911fa577b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discussion_fact_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "extracted_facts_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "missing_fields_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "risk_flags_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "source_text_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "milestones",
        sa.Column(
            "source_plan_item_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.create_index(
        "uq_agreement_milestone_key",
        "milestones",
        ["agreement_version_id", "source_plan_item_key"],
        unique=True,
        sqlite_where=sa.text("source_plan_item_key IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_agreement_milestone_key",
        table_name="milestones",
        sqlite_where=sa.text("source_plan_item_key IS NOT NULL"),
    )
    op.drop_column("milestones", "source_plan_item_key")
    op.drop_table("discussion_fact_snapshots")
    # ### end Alembic commands ###
